### ISSUE TITLE
非常棒，已星标，催更！

### ISSUE THREAD

**Issue by ZTOA10** [srsng/cozy-reader#4]
项目体验了一下，非常棒，清爽，响应也快，功能基本已经完善，就差细节优化了！
1、刚开始使用时，打开页面，因为太简洁，还以为是个外语软件。（要不左上角鼠标移图标功能有中文提示？）
2、要是有绿色版免安装就更好了，懒人最爱，也方便进一步广泛宣传这个软件。
3、拖动窗口文字内容会随着变化，可惜两边留白太多了，缩小的时候压缩得厉害，很不得劲，能给个设置就更好了
4、对于漫画版的epub，图片之间有缝隙会很影响阅读体验，所以希望有可以设置line height:为0的权限（如果方便的话可以给个自定义阅读格式的设置储存项，这样我就可以随时切换设置进行文本阅读或者漫画阅读了）

**Comment by srsng** [comment]
1. 图标功能提示会加上，但是使用简单的英文
2. 版本发布是通过tauri打包，不直接提供免安装版；软件现在安装之后得到只有一个exe（windows环境下），实际上可以直接单独运行。
3. 两边的边距可以调整左下设置的第一个选项（reader width）
4. 行高也可以在设置中调整，下个版本增加直接设置行高为0的选项

**Comment by ZTOA10** [comment]
大佬效率这么高的么，基本解决我的需求了，牛逼！

**Comment by ZTOA10** [comment]
大佬，漫画模式，高度边距为0的情况下还是会出现空白，应该是font size不能设置为0的原因，有办法再优化一下吗，下面的是图示和漫画的附件
![image](https://github.com/user-attachments/assets/023d27c5-606c-4eb4-8169-2707c7a3a27b)
[Reality Quest.zip](https://github.com/user-attachments/files/17268995/Reality.Quest.zip)

**Comment by srsng** [comment]
已经修改了
