### ISSUE TITLE
非全屏窗口阅读时文字溢出

### ISSUE THREAD

**Issue by meichiny** [srsng/cozy-reader#5]
非全屏下阅读，调整窗口的宽度，代码文字溢出窗口，显示不完整。
![image](https://github.com/user-attachments/assets/661387b1-b375-460d-8660-bf2b17fb11ab)

**Comment by srsng** [comment]
麻烦提供一下这本电子书

**Comment by srsng** [comment]
麻烦附件上传提供一下这本电子书

**Comment by meichiny** [comment]
> 麻烦附件上传提供一下这本电子书

[Python编程：从入门到实践第3版.zip](https://github.com/user-attachments/files/17267798/Python.3.zip)

**Comment by srsng** [comment]
针对这本书可能的情况已经优化，试一下最新版本。

代码等强制换行可能导致阅读理解出错，建议让代码在一行完全显示

**Comment by meichiny** [comment]
> 针对这本书可能的情况已经优化，试一下最新版本。
> 
> 代码等强制换行可能导致阅读理解出错，建议让代码在一行完全显示

OK啦，谢谢
